"""initial schema

Revision ID: e8eb0ab39b20
Revises: 
Create Date: 2026-07-22 07:06:16.998525
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'e8eb0ab39b20'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # CITEXT columns (items/line_items normalized_name) need the extension.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('parent_id', 'name', name='parent_name')
    )
    op.create_table('receipts',
    sa.Column('store_name', sa.Text(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), server_default='EUR', nullable=False),
    sa.Column('status', sa.Text(), server_default='uploaded', nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'done', 'needs_review', 'failed')", name=op.f('ck_receipts_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts'))
    )
    op.create_table('items',
    sa.Column('normalized_name', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_items_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_items_normalized_name'))
    )
    op.create_table('line_items',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', postgresql.CITEXT(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_class', sa.Text(), nullable=True),
    sa.Column('line_type', sa.Text(), server_default='product', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("line_type IN ('product', 'deposit', 'discount')", name=op.f('ck_line_items_line_type')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_line_items_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_line_items_item_id_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('fk_line_items_receipt_id_receipts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_items'))
    )
    op.create_index(op.f('ix_line_items_normalized_name'), 'line_items', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_items_normalized_name'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_table('items')
    op.drop_table('receipts')
    op.drop_table('categories')
    # ### end Alembic commands ###
